version: 0.0
os: linux
files:
  - source: /
    destination: /data/codedeploy

permissions:
  - object: /
    pattern: "**"
    owner: node
    group: app
    mode : 750

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/delete.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
